import Providers from "@/components/Providers";

import { authOptions } from "@/lib/auth/authOptions";

import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Reports",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <Providers session={session}>
      <main className="w-full font-[family-name:var(--font-satoshi)]">
        {children}
      </main>
    </Providers>
  );
}
