/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the patternreveal SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx workspacesGet.ts
 */

import { Patternreveal } from "patternreveal";

const patternreveal = new Patternreveal({
  token: "PATTERN_REVEAL_API_KEY",
});

async function main() {
  const result = await patternreveal.get({
    idOrSlug: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
