import prisma from "@/lib/prisma";
import { notFound } from "next/navigation";
import { constructMetadata } from "@/utils/functions/construct-metadata";

type PageProps = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({
  params
}: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  try {
    const report = await prisma.reflection.findUnique({
      where: { id },
      include: {
        analysisReport: true,
        user: {
          select: { name: true }
        }
      }
    });

    if (!report) {
      return constructMetadata({
        title: "Report Not Found - PatternReveal",
        description:
          "The requested relationship analysis report could not be found.",
        noIndex: true
      });
    }

    const authorName = report.user?.name || "Anonymous";

    return constructMetadata({
      title: `${report.title} - Relationship Analysis Report`,
      description: `A relationship pattern analysis report by ${authorName}. Insights into relationship dynamics, emotional patterns, and communication behaviors generated by PatternReveal.xyz.`,
      image: "/images/example-report.png"
    });
  } catch (error) {
    return constructMetadata({
      title: "Relationship Analysis Report - PatternReveal",
      description:
        "A detailed relationship pattern analysis report with AI-powered insights and expert guidance.",
      noIndex: true
    });
  }
}

export default async function PublicReportPage({ params }: PageProps) {
  const { id } = await params;
  const report = await prisma.reflection.findUnique({
    where: {
      id: id
    },
    include: {
      analysisReport: true,
      user: true
    }
  });

  if (!report) {
    notFound();
  }

  return <div>{report?.title}</div>;
}
