/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { PatternrevealCore } from "../core.js";
import { encodeJSON, encodeSimple } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import * as errors from "../models/errors/index.js";
import { PatternrevealError } from "../models/errors/patternrevealerror.js";
import { ResponseValidationError } from "../models/errors/responsevalidationerror.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

/**
 * Update a workspace
 *
 * @remarks
 * Update a workspace by ID or slug.
 */
export function workspacesUpdate(
  client: PatternrevealCore,
  idOrSlug: string,
  requestBody?: operations.UpdateWorkspaceRequestBody | undefined,
  options?: RequestOptions,
): APIPromise<
  Result<
    models.WorkspaceSchema,
    | errors.BadRequestError
    | errors.UnauthorizedError
    | errors.ForbiddenError
    | errors.NotFoundError
    | errors.ConflictError
    | errors.InviteExpiredError
    | errors.UnprocessableEntityError
    | errors.RateLimitExceededError
    | errors.InternalServerError
    | PatternrevealError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >
> {
  return new APIPromise($do(
    client,
    idOrSlug,
    requestBody,
    options,
  ));
}

async function $do(
  client: PatternrevealCore,
  idOrSlug: string,
  requestBody?: operations.UpdateWorkspaceRequestBody | undefined,
  options?: RequestOptions,
): Promise<
  [
    Result<
      models.WorkspaceSchema,
      | errors.BadRequestError
      | errors.UnauthorizedError
      | errors.ForbiddenError
      | errors.NotFoundError
      | errors.ConflictError
      | errors.InviteExpiredError
      | errors.UnprocessableEntityError
      | errors.RateLimitExceededError
      | errors.InternalServerError
      | PatternrevealError
      | ResponseValidationError
      | ConnectionError
      | RequestAbortedError
      | RequestTimeoutError
      | InvalidRequestError
      | UnexpectedClientError
      | SDKValidationError
    >,
    APICall,
  ]
> {
  const input: operations.UpdateWorkspaceRequest = {
    idOrSlug: idOrSlug,
    requestBody: requestBody,
  };

  const parsed = safeParse(
    input,
    (value) => operations.UpdateWorkspaceRequest$outboundSchema.parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;
  const body = encodeJSON("body", payload.RequestBody, { explode: true });

  const pathParams = {
    idOrSlug: encodeSimple("idOrSlug", payload.idOrSlug, {
      explode: false,
      charEncoding: "percent",
    }),
  };

  const path = pathToFunc("/workspaces/{idOrSlug}")(pathParams);

  const headers = new Headers(compactMap({
    "Content-Type": "application/json",
    Accept: "application/json",
  }));

  const secConfig = await extractSecurity(client._options.token);
  const securityInput = secConfig == null ? {} : { token: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    options: client._options,
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "updateWorkspace",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.token,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "PATCH",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    userAgent: client._options.userAgent,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: [
      "400",
      "401",
      "403",
      "404",
      "409",
      "410",
      "422",
      "429",
      "4XX",
      "500",
      "5XX",
    ],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const responseFields = {
    HttpMeta: { Response: response, Request: req },
  };

  const [result] = await M.match<
    models.WorkspaceSchema,
    | errors.BadRequestError
    | errors.UnauthorizedError
    | errors.ForbiddenError
    | errors.NotFoundError
    | errors.ConflictError
    | errors.InviteExpiredError
    | errors.UnprocessableEntityError
    | errors.RateLimitExceededError
    | errors.InternalServerError
    | PatternrevealError
    | ResponseValidationError
    | ConnectionError
    | RequestAbortedError
    | RequestTimeoutError
    | InvalidRequestError
    | UnexpectedClientError
    | SDKValidationError
  >(
    M.json(200, models.WorkspaceSchema$inboundSchema),
    M.jsonErr(400, errors.BadRequestError$inboundSchema),
    M.jsonErr(401, errors.UnauthorizedError$inboundSchema),
    M.jsonErr(403, errors.ForbiddenError$inboundSchema),
    M.jsonErr(404, errors.NotFoundError$inboundSchema),
    M.jsonErr(409, errors.ConflictError$inboundSchema),
    M.jsonErr(410, errors.InviteExpiredError$inboundSchema),
    M.jsonErr(422, errors.UnprocessableEntityError$inboundSchema),
    M.jsonErr(429, errors.RateLimitExceededError$inboundSchema),
    M.jsonErr(500, errors.InternalServerError$inboundSchema),
    M.fail("4XX"),
    M.fail("5XX"),
  )(response, req, { extraFields: responseFields });
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
