workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    PatternReveal API:
        inputs:
            - location: ../openapi.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/patternreveal/api/pattern-reveal-api
targets:
    patternreveal:
        target: typescript
        source: PatternReveal API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/patternreveal/api/pattern-reveal-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
