import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const satoshi = localFont({
  src: "./fonts/Satoshi.ttf",
  variable: "--font-satoshi"
});
const erode = localFont({
  src: "./fonts/Erode.ttf",
  variable: "--font-erode"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable} ${erode.variable} antialiased`}>
        <Toaster />
        <NuqsAdapter>{children}</NuqsAdapter>
      </body>
    </html>
  );
}
