import type { Metadata } from "next";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

export const metadata: Metadata = {
  title: "Privacy Policy | PatternReveal",
  description:
    "PatternReveal Privacy Policy - How we collect, use, and protect your personal data",
};

export default function PrivacyPolicy() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <div className="prose prose-gray dark:prose-invert max-w-none">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

        <p className="text-lg text-muted-foreground mb-8">
          <strong>Last updated:</strong> {new Date().toLocaleDateString()}
        </p>

        <p className="mb-6">
          At PatternReveal ("we," "our," or "us"), we are committed to
          protecting your privacy and personal information. This Privacy Policy
          explains how we collect, use, disclose, and safeguard your information
          when you use our relationship reflection and pattern analysis
          platform.
        </p>

        <p className="mb-6">
          We use your data to provide and improve our Service. By using our
          Service, you agree to the collection and use of information in
          accordance with this policy. Unless otherwise defined in this Privacy
          Policy, the terms used in this Privacy Policy have the same meanings
          as in our Terms and Conditions.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">1. Definitions</h2>

        <p className="mb-4">
          Below is a list of definitions for the terms used in this Privacy
          Policy:
        </p>

        <Table className="mb-6">
          <TableHeader>
            <TableRow>
              <TableHead className="px-8 py-6 font-semibold">Term</TableHead>
              <TableHead className="px-6 py-4 font-semibold">
                Definition
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">Service</TableCell>
              <TableCell className="px-6 py-4">
                PatternReveal website and application operated by PatternReveal
                for relationship reflection and pattern analysis.
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">
                Personal Data
              </TableCell>
              <TableCell className="px-6 py-4">
                Data about a living individual who can be identified from those
                data (or from those and other information either in our
                possession or likely to come into our possession).
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">
                Usage Data
              </TableCell>
              <TableCell className="px-6 py-4">
                Data collected automatically either generated by the use of
                Service or from Service infrastructure itself (for example, the
                duration of a page visit).
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">Cookies</TableCell>
              <TableCell className="px-6 py-4">
                Small files stored on your device (computer or mobile device).
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">
                Data Controller
              </TableCell>
              <TableCell className="px-6 py-4">
                A natural or legal person who determines the purposes for which
                and the manner in which any personal data are processed. For the
                purpose of this Privacy Policy, we are a Data Controller of your
                data.
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">
                Data Processors
              </TableCell>
              <TableCell className="px-6 py-4">
                Any natural or legal person who processes the data on behalf of
                the Data Controller. We may use the services of various Service
                Providers to process your data more effectively.
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="px-8 py-6 font-medium">User</TableCell>
              <TableCell className="px-6 py-4">
                The individual using our Service. The User corresponds to the
                Data Subject, who is the subject of Personal Data.
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          2. Information Collection and Use
        </h2>

        <p className="mb-4">
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">2.1 Personal Data</h3>
        <p className="mb-4">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you ("Personal Data"). Personally identifiable information
          may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            <strong>Account Information:</strong> Name, email address, password
            (hashed), profile image
          </li>

          <li>
            <strong>Payment Information:</strong> Billing details processed
            through Paddle (we do not store payment card information)
          </li>
        </ul>

        <p className="mb-6">
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">2.2 Usage Data</h3>
        <p className="mb-4">
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through a mobile
          device ("Usage Data").
        </p>
        <p className="mb-4">This Usage Data may include information such as:</p>
        <ul className="list-disc pl-6 mb-6">
          <li>Your computer's Internet Protocol address (e.g. IP address)</li>
          <li>Browser type and browser version</li>
          <li>The pages of our Service that you visit</li>
          <li>The time and date of your visit</li>
          <li>The time spent on those pages</li>
          <li>Unique device identifiers and other diagnostic data</li>
          <li>Mobile device information (when accessing via mobile)</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">
          2.3 Reflection Content
        </h3>
        <p className="mb-4">
          We collect and process highly personal reflection data including:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>Personal relationship reflections and stories</li>
          <li>Emotional experiences and triggers</li>
          <li>Communication patterns and dynamics</li>
          <li>Relationship context and interactions</li>
          <li>Mood tracking data</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">
          2.4 Analytics and Usage Data
        </h3>
        <p className="mb-4">
          We collect analytical data to improve our services:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            Pattern analysis results (emotional, communication, behavioral
            patterns)
          </li>
          <li>
            AI analysis metadata (processing time, model used, confidence
            levels)
          </li>
          <li>
            Usage statistics (reflection counts, feature usage, plan limits)
          </li>
          <li>Performance metrics and error logs</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">2.5 Cookies Data</h3>
        <p className="mb-4">
          We use cookies and similar tracking technologies to track activity on
          our Service and hold certain information. Cookies are files with small
          amount of data which may include an anonymous unique identifier.
        </p>
        <p className="mb-4">We use the following types of cookies:</p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            <strong>Essential Cookies:</strong> Required for basic website
            functionality, authentication, and security
          </li>
          <li>
            <strong>Analytics Cookies:</strong> Used by PostHog and Tinybird to
            understand how users interact with our Service
          </li>
          <li>
            <strong>Performance Cookies:</strong> Used by Sentry to monitor
            application performance and error tracking
          </li>
          <li>
            <strong>Marketing Cookies:</strong> Used for targeted advertising
            and marketing campaigns (with your consent)
          </li>
        </ul>
        <p className="mb-4">
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">3. Use of Data</h2>

        <p className="mb-4">
          PatternReveal uses the collected data for various purposes:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>to provide and maintain our Service</li>
          <li>to notify you about changes to our Service</li>
          <li>
            to allow you to participate in interactive features of our Service
            when you choose to do so
          </li>
          <li>to provide customer support</li>
          <li>
            to gather analysis or valuable information so that we can improve
            our Service
          </li>
          <li>to monitor the usage of our Service</li>
          <li>to detect, prevent and address technical issues</li>
          <li>to fulfill any other purpose for which you provide it</li>
          <li>
            to carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection
          </li>
          <li>
            to provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.
          </li>
          <li>
            to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
          </li>
          <li>
            in any other way we may describe when you provide the information
          </li>
          <li>for any other purpose with your consent</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">
          3.1 AI Analysis and Processing
        </h3>
        <p className="mb-4">
          Your reflection content is processed by AI systems to:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>Analyze emotional patterns and triggers</li>
          <li>Identify communication styles and effectiveness</li>
          <li>Detect behavioral patterns and cycles</li>
          <li>Assess relationship dynamics and health</li>
          <li>Generate personalized insights and recommendations</li>
          <li>Identify potential safety concerns or abusive patterns</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          4. Retention of Data
        </h2>

        <p className="mb-6">
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>

        <p className="mb-6">
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          5. Transfer of Data
        </h2>

        <p className="mb-6">
          Your information, including Personal Data, may be transferred to – and
          maintained on – computers located outside of your state, province,
          country or other governmental jurisdiction where the data protection
          laws may differ from those of your jurisdiction.
        </p>

        <p className="mb-6">
          If you are located outside United States and choose to provide
          information to us, please note that we transfer the data, including
          Personal Data, to United States and process it there.
        </p>

        <p className="mb-6">
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>

        <p className="mb-6">
          PatternReveal will take all the steps reasonably necessary to ensure
          that your data is treated securely and in accordance with this Privacy
          Policy and no transfer of your Personal Data will take place to an
          organisation or a country unless there are adequate controls in place
          including the security of your data and other personal information.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          6. Disclosure of Data
        </h2>

        <p className="mb-4">
          We may disclose personal information that we collect, or you provide:
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">
          6.1 Disclosure for Law Enforcement
        </h3>
        <p className="mb-6">
          Under certain circumstances, we may be required to disclose your
          Personal Data if required to do so by law or in response to valid
          requests by public authorities.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">
          6.2 Business Transaction
        </h3>
        <p className="mb-6">
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">6.3 Other Cases</h3>
        <p className="mb-4">We may disclose your information also:</p>
        <ul className="list-disc pl-6 mb-6">
          <li>to our subsidiaries and affiliates</li>
          <li>
            to contractors, service providers, and other third parties we use to
            support our business
          </li>
          <li>to fulfill the purpose for which you provide it</li>
          <li>
            for any other purpose disclosed by us when you provide the
            information
          </li>
          <li>with your consent in any other cases</li>
          <li>
            if we believe disclosure is necessary or appropriate to protect the
            rights, property, or safety of the Company, our customers, or others
          </li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">
          6.4 Third-Party Service Providers
        </h3>
        <p className="mb-4">
          We share information with trusted third-party services:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            <strong>Paddle:</strong> Payment processing and subscription
            management
          </li>
          <li>
            <strong>Resend:</strong> Email delivery and communication services
          </li>
          <li>
            <strong>Tinybird:</strong> Analytics data processing and storage
          </li>
          <li>
            <strong>PostHog:</strong> Product analytics and user behavior
            tracking
          </li>
          <li>
            <strong>Sentry:</strong> Error monitoring and performance tracking
          </li>
          <li>
            <strong>Google:</strong> Authentication services (when using Google
            sign-in)
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          7. Security of Data
        </h2>

        <p className="mb-4">
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>

        <p className="mb-4">
          We implement comprehensive security measures to protect your data:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>End-to-end encryption for sensitive data transmission</li>
          <li>Secure data storage with industry-standard encryption</li>
          <li>Access controls and authentication mechanisms</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          8. Your Data Protection Rights Under General Data Protection
          Regulation (GDPR)
        </h2>

        <p className="mb-4">
          If you're located in the European Union (EU) or European Economic Area
          (EEA), you are entitled to specific rights under the{" "}
          <a
            href="https://eur-lex.europa.eu/eli/reg/2016/679/oj"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-600 hover:text-blue-800 underline"
          >
            General Data Protection Regulation (GDPR)
          </a>
          . At PatternReveal, we take data protection seriously and are
          committed to safeguarding your personal information.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">
          8.1 Your Privacy Rights
        </h3>
        <p className="mb-4">
          We respect your right to control your personal data. If you'd like to
          access, update, restrict, or delete the information we hold about you,
          just email us at info@patternreveal.xyz. Under GDPR, you may have the
          right to:
        </p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            <strong>Access</strong> the personal data we hold about you
          </li>
          <li>
            <strong>Request corrections</strong> to inaccurate or incomplete
            information
          </li>
          <li>
            <strong>Delete your data</strong> under certain conditions
          </li>
          <li>
            <strong>Limit or object</strong> to how your data is processed
          </li>
          <li>
            <strong>Receive your data</strong> in a portable, machine-readable
            format
          </li>
          <li>
            <strong>Withdraw consent</strong> where processing is based on
            consent—at any time, without affecting prior lawful processing
          </li>
        </ul>

        <p className="mb-6">
          We may need to verify your identity before fulfilling certain
          requests. Keep in mind, if you choose to delete or restrict certain
          data, some services may become unavailable.
        </p>

        <p className="mb-6">
          You also have the right to file a complaint with your local Data
          Protection Authority if you believe your data is being handled in a
          way that doesn't comply with GDPR.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          9. Your Data Protection Rights under the California Consumer Privacy
          Act (CCPA)
        </h2>

        <p className="mb-4">
          If you are a California resident, you are entitled to learn what data
          we collect about you, ask to delete your data and not to sell (share)
          it. To exercise your data protection rights, you can make certain
          requests and ask us:
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">
          9.1 What personal information we have about you
        </h3>
        <p className="mb-4">If you make this request, we will return to you:</p>
        <ul className="list-disc pl-6 mb-6">
          <li>
            The categories of personal information we have collected about you
          </li>
          <li>
            The categories of sources from which we collect your personal
            information
          </li>
          <li>
            The business or commercial purpose for collecting or selling your
            personal information
          </li>
          <li>
            The categories of third parties with whom we share personal
            information
          </li>
          <li>
            The specific pieces of personal information we have collected about
            you
          </li>
          <li>
            A list of categories of personal information that we have sold,
            along with the category of any other company we sold it to. If we
            have not sold your personal information, we will inform you of that
            fact
          </li>
          <li>
            A list of categories of personal information that we have disclosed
            for a business purpose, along with the category of any other company
            we shared it with
          </li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-3">
          9.2 To delete your personal information
        </h3>
        <p className="mb-6">
          If you make this request, we will delete the personal information we
          hold about you as of the date of your request from our records and
          direct any service providers to do the same. In some cases, deletion
          may be accomplished through de-identification of the information. If
          you choose to delete your personal information, you may not be able to
          use certain functions that require your personal information to
          operate.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-3">
          9.3 To stop selling your personal information
        </h3>
        <p className="mb-6">
          We don't sell or rent your personal information to any third parties
          for any purpose. You are the only owner of your Personal Data and can
          request disclosure or deletion at any time.
        </p>

        <p className="mb-6">
          To exercise your California data protection rights described above,
          please send your request(s) to info@patternreveal.xyz.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          10. Service Providers (Subprocessors)
        </h2>

        <p className="mb-6">
          We may employ third party companies and individuals to facilitate our
          Service ("Subprocessors"), provide Service on our behalf, perform
          Service-related services or assist us in analysing how our Service is
          used.
        </p>

        <p className="mb-6">
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          11. Links to Other Sites
        </h2>

        <p className="mb-6">
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party's site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>

        <p className="mb-6">
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          12. Children's Privacy
        </h2>

        <p className="mb-6">
          Our Services are not intended for use by children under the age of 18
          ("Child" or "Children").
        </p>

        <p className="mb-6">
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us at info@patternreveal.xyz.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          13. Changes to This Privacy Policy
        </h2>

        <p className="mb-6">
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>

        <p className="mb-6">
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update "effective
          date" at the top of this Privacy Policy.
        </p>

        <p className="mb-6">
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">14. Contact Us</h2>

        <p className="mb-4">
          If you have any questions about this Privacy Policy, please contact us
          at info@patternreveal.xyz.
        </p>
      </div>
    </div>
  );
}
