/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export const Plan = {
  Free: "free",
  Pro: "pro",
} as const;
export type Plan = ClosedEnum<typeof Plan>;

export const Role = {
  Owner: "OWNER",
  Member: "MEMBER",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type User = {
  role: Role;
};

export type WorkspaceSchema = {
  id: string;
  name: string;
  slug: string;
  logo?: string | null | undefined;
  inviteCode: string | null;
  billingCycleStart: number;
  plan: Plan;
  totalReflections: number;
  usage: number;
  usageLimit: number;
  reflectionsUsage: number;
  reflectionsLimit: number;
  aiUsage: number;
  aiLimit: number;
  usersLimit: number;
  store: { [k: string]: any };
  users: Array<User>;
  createdAt: string;
  updatedAt: string;
  paddleCustomerId: string | null;
};

/** @internal */
export const Plan$inboundSchema: z.ZodNativeEnum<typeof Plan> = z.nativeEnum(
  Plan,
);

/** @internal */
export const Plan$outboundSchema: z.ZodNativeEnum<typeof Plan> =
  Plan$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Plan$ {
  /** @deprecated use `Plan$inboundSchema` instead. */
  export const inboundSchema = Plan$inboundSchema;
  /** @deprecated use `Plan$outboundSchema` instead. */
  export const outboundSchema = Plan$outboundSchema;
}

/** @internal */
export const Role$inboundSchema: z.ZodNativeEnum<typeof Role> = z.nativeEnum(
  Role,
);

/** @internal */
export const Role$outboundSchema: z.ZodNativeEnum<typeof Role> =
  Role$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Role$ {
  /** @deprecated use `Role$inboundSchema` instead. */
  export const inboundSchema = Role$inboundSchema;
  /** @deprecated use `Role$outboundSchema` instead. */
  export const outboundSchema = Role$outboundSchema;
}

/** @internal */
export const User$inboundSchema: z.ZodType<User, z.ZodTypeDef, unknown> = z
  .object({
    role: Role$inboundSchema,
  });

/** @internal */
export type User$Outbound = {
  role: string;
};

/** @internal */
export const User$outboundSchema: z.ZodType<User$Outbound, z.ZodTypeDef, User> =
  z.object({
    role: Role$outboundSchema,
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace User$ {
  /** @deprecated use `User$inboundSchema` instead. */
  export const inboundSchema = User$inboundSchema;
  /** @deprecated use `User$outboundSchema` instead. */
  export const outboundSchema = User$outboundSchema;
  /** @deprecated use `User$Outbound` instead. */
  export type Outbound = User$Outbound;
}

export function userToJSON(user: User): string {
  return JSON.stringify(User$outboundSchema.parse(user));
}

export function userFromJSON(
  jsonString: string,
): SafeParseResult<User, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => User$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'User' from JSON`,
  );
}

/** @internal */
export const WorkspaceSchema$inboundSchema: z.ZodType<
  WorkspaceSchema,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  logo: z.nullable(z.string()).default(null),
  inviteCode: z.nullable(z.string()),
  billingCycleStart: z.number(),
  plan: Plan$inboundSchema,
  totalReflections: z.number(),
  usage: z.number(),
  usageLimit: z.number(),
  reflectionsUsage: z.number(),
  reflectionsLimit: z.number(),
  aiUsage: z.number(),
  aiLimit: z.number(),
  usersLimit: z.number(),
  store: z.record(z.any()),
  users: z.array(z.lazy(() => User$inboundSchema)),
  createdAt: z.string(),
  updatedAt: z.string(),
  paddleCustomerId: z.nullable(z.string()),
});

/** @internal */
export type WorkspaceSchema$Outbound = {
  id: string;
  name: string;
  slug: string;
  logo: string | null;
  inviteCode: string | null;
  billingCycleStart: number;
  plan: string;
  totalReflections: number;
  usage: number;
  usageLimit: number;
  reflectionsUsage: number;
  reflectionsLimit: number;
  aiUsage: number;
  aiLimit: number;
  usersLimit: number;
  store: { [k: string]: any };
  users: Array<User$Outbound>;
  createdAt: string;
  updatedAt: string;
  paddleCustomerId: string | null;
};

/** @internal */
export const WorkspaceSchema$outboundSchema: z.ZodType<
  WorkspaceSchema$Outbound,
  z.ZodTypeDef,
  WorkspaceSchema
> = z.object({
  id: z.string(),
  name: z.string(),
  slug: z.string(),
  logo: z.nullable(z.string()).default(null),
  inviteCode: z.nullable(z.string()),
  billingCycleStart: z.number(),
  plan: Plan$outboundSchema,
  totalReflections: z.number(),
  usage: z.number(),
  usageLimit: z.number(),
  reflectionsUsage: z.number(),
  reflectionsLimit: z.number(),
  aiUsage: z.number(),
  aiLimit: z.number(),
  usersLimit: z.number(),
  store: z.record(z.any()),
  users: z.array(z.lazy(() => User$outboundSchema)),
  createdAt: z.string(),
  updatedAt: z.string(),
  paddleCustomerId: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace WorkspaceSchema$ {
  /** @deprecated use `WorkspaceSchema$inboundSchema` instead. */
  export const inboundSchema = WorkspaceSchema$inboundSchema;
  /** @deprecated use `WorkspaceSchema$outboundSchema` instead. */
  export const outboundSchema = WorkspaceSchema$outboundSchema;
  /** @deprecated use `WorkspaceSchema$Outbound` instead. */
  export type Outbound = WorkspaceSchema$Outbound;
}

export function workspaceSchemaToJSON(
  workspaceSchema: WorkspaceSchema,
): string {
  return JSON.stringify(WorkspaceSchema$outboundSchema.parse(workspaceSchema));
}

export function workspaceSchemaFromJSON(
  jsonString: string,
): SafeParseResult<WorkspaceSchema, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WorkspaceSchema$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WorkspaceSchema' from JSON`,
  );
}
